fix: Handle deletion of files gracefully on compile
facebook/stylex pull request #680
Opened 2024-09-06 09:20 UTC by budde377

Catch and display error when `compileDirectory` fails to delete a file.

## What changed / motivation ?

When running the CLI on watch mode and making file system changes to the watched folder, the CLI consistently fails to delete a missing file. This causes the CLI to exit and not restart drastically reducing the usability of the tool during active development. 

## Linked PR/Issues

## Additional Context

```
Error: ENOENT: no such file or directory, lstat '<project-file>'
     at Object.rmSync (node:fs:1261:13)
     at <project-path>/node_modules/@stylexjs/cli/lib/index.js:199:12
     at Array.forEach (<anonymous>)
     at compileDirectory (<project-path>/node_modules/@stylexjs/cli/lib/index.js:196:19)
     at Client.<anonymous> (<project-path>/node_modules/@stylexjs/cli/lib/index.js:350:5)
     at Client.emit (node:events:519:28)
     at BunserBuf.<anonymous> (<project-path>/node_modules/fb-watchman/index.js:94:14)
     at BunserBuf.emit (node:events:519:28)
     at BunserBuf.process (<project-path>/node_modules/bser/index.js:292:10)
     at <project-path>/node_modules/bser/index.js:247:12 {
   errno: -2,
   code: 'ENOENT',
   syscall: 'lstat',
   path: '<project-file>'
 }
```

Screenshots, Tests, Anything Else

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

2024-09-09 07:50 UTC, nmn requested changes
Can you please fix this typo?

2024-09-09 07:50 UTC, nmn commented on packages/cli/src/transform.js
> +          console.error('[stylex] failed to delete file: ', error);
There's a typo here.

```suggestion
          console.error('[stylex] failed to delete file: ', err);
```

2024-09-09 20:28 UTC, Jta26 commented
Hmm. I'm pretty sure the failure in the CI is not due to your changes.

2024-09-09 20:31 UTC, Jta26 approved these changes

2024-09-10 07:02 UTC, nmn commented
I'm not sure why that one signal is failing. I don't see any issue with the code change itself. Trying to rebase.

2024-09-10 07:02 UTC, nmn approved these changes
Makes sense.

2024-09-10 07:14 UTC, nmn commented
Something about this change is making that one signal fail. Not quite sure why this might be. The error message seems to be using an invalid Github URL so it feels like some strange edge-case.

I'll continue to try somethings to get this change merged.

2024-09-16 20:52 UTC, budde377 commented
I've patched and run the version currently in the repo and it works well. I looks like this problem has been solved.

2024-09-16 20:52 UTC, closed without merging