Feat/auto aliases
facebook/stylex pull request #810
Opened 2024-12-16 18:59 UTC by p0nch000

# [Feature] Automatically Discover StyleX Aliases from Configuration Files

## Linked Issues
Fixes #765

---

## Overview
This PR enhances the **StyleX Babel plugin** to automatically discover alias configurations from `package.json` and `tsconfig.json`. It ensures normalized paths for cross-platform compatibility and maintains **backward compatibility** with existing manual configurations.

---

## Implementation Details
- **JSON5 Parser**: Added to handle `tsconfig.json` files with comments or trailing commas.
- **Alias Discovery**:
  - Parses `package.json` for `stylex.aliases`.
  - Parses `tsconfig.json` for `compilerOptions.paths` and resolves paths relative to `baseUrl`.
- **Merge Configurations**:
  - Combines configurations from `package.json` and `tsconfig.json`.
  - Manual alias configurations override both.
- **Normalized Paths**: Path separators are standardized for cross-platform compatibility.
- **Error Handling**: Gracefully handles missing or malformed configuration files.
- **Comprehensive Tests**: Added tests to ensure correctness of the new functionality.

---

## Test Coverage
The following scenarios are tested:
1. **Alias Discovery**:
   - From `package.json`.
   - From `tsconfig.json`.
2. **Configuration Merging**:
   - Merges `package.json` and `tsconfig.json`.
3. **Manual Overrides**:
   - Ensures manual configurations take precedence.
4. **Error Handling**:
   - Handles missing or invalid files gracefully.

### Example Configurations:
#### `package.json`:
```json
{
  "stylex": {
    "aliases": {
      "@components": "./src/components",
      "@utils/*": ["./src/utils/*"]
    }
  }
}
```

#### `tsconfig.json`:
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": ["src/components/*"],
      "@utils/*": ["src/utils/*"]
    }
  }
}
```

---

## Code Changes

### 1. `state-manager.js` (Alias Discovery):
- **New Functionality**:
  - `loadAliases`: Handles discovery and merging of aliases.
  - `normalizePath`: Normalizes path separators.
  - `normalizeAliases`: Converts alias paths to arrays of normalized absolute paths.
  - `findProjectRoot`: Locates the root directory containing configuration files.

### 2. `stylex-transform-alias-config-test.js`:
- **Added Unit Tests**:
  - Alias discovery from `package.json`.
  - Alias discovery from `tsconfig.json`.
  - Merging of configurations.
  - Handling missing or invalid files.
  - Manual configuration override behavior.

---

## Potential Future Improvements
1. **Enhanced Test Cases**:
   - Complex alias patterns with wildcards.
   - Nested directory structures.
   - Edge cases in path resolution.

2. **Additional Features**:
   - Support for other configuration sources like Webpack config.
   - More granular control over alias resolution priorities.

3. **Performance Optimizations**:
   - Caching of discovered configurations.
   - Smarter file system traversal.

---

## Pre-flight Checklist
- [x] I have read the [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/CONTRIBUTING.md).
- [x] Performed a self-review of my code.
- [x] Added tests for the new functionality.
- [x] Verified cross-platform compatibility.
- [x] Ensured backward compatibility with existing configurations.

---

## Feedback
Feedback is welcome, particularly for:
- Additional test cases to consider.
- Improvements to performance or alias resolution edge cases.

2024-12-16 19:06 UTC, p0nch000 commented
Hey @nmn, this is my initial implementation for the issue. Let me know if there are any additional test cases or improvements you'd like me to include. I’m happy to iterate further based on your feedback

2024-12-17 05:57 UTC, nmn commented
> Parses package.json for stylex.aliases.

We don't want to add a new `stylex.aliases` option to the `package.json`. Instead, please look for the native aliases configuration supported by Node.js:

- https://nodejs.org/api/packages.html#imports
- https://nodejs.org/api/packages.html#subpath-imports
- https://betterprogramming.pub/the-native-way-to-configure-path-aliases-in-frontend-projects-5db70f19a6e0#02ec

2024-12-17 06:01 UTC, nmn requested changes
Great start! Please fix the failing tests and address the comments.

2024-12-17 06:01 UTC, nmn commented on packages/babel-plugin/src/utils/state-manager.js
> +  findProjectRoot(filePath: string): string {
See the `getPackageNameAndPath` method which does something similar and try to share code between this and that method.

2024-12-17 19:53 UTC, p0nch000 commented
Hey @nmn fixed all the changes you requested, i just couldnt pass the size test but apart from that i think its all ready, also updated the PR description and the unit tests, let me know if more changes are needed :)

2024-12-18 01:14 UTC, nmn requested changes
Nearly there. I'll do some more testing before I merge, but I don't see any issues in the code review.

2024-12-18 01:14 UTC, nmn commented on package.json
> +    "json5": "^2.2.3"
This needs to be added as a dependency for the babel-plugin.

2024-12-21 09:15 UTC, nmn approved these changes
Changes look good in general. I will test a bit more before merging.

2025-01-02 18:55 UTC, nmn commented
I did  some local testing and there is an issue with path normalization which makes this PR not quite work as expected.

There are two issues:
1. The trailing `/*` is stripped from the alias definitions which is needed for StyleX to correctly match all paths after the given prefix.
2. Paths such as `.` or `./*` are not normalized to the correct absolute paths.

This means that even though all the logic to discover the configurations is working correctly, it doesn't work in practice.

You can remove the `aliases` option the babel config for the nextjs exampple to test this yourself.

2025-01-02 19:04 UTC, nmn requested changes
Please fix the path resolutions.

2025-01-02 19:04 UTC, nmn commented on packages/babel-plugin/src/utils/state-manager.js
> +        }
Making this change fixed the problem for `tsconfig.json` files

Similar fixes might be needed for the other config files as well.

```suggestion
        if (tsconfig.compilerOptions?.paths) {
          tsconfigAliases = Object.fromEntries(
            Object.entries(tsconfig.compilerOptions.paths).map(
              ([key, value]) => [
                key,
                (Array.isArray(value) ? value : [value]).map((p) => {
                  const endsWithStar = p.endsWith('/*');

                  let basePath = p.replace(/\/\*$/, '');
                  if (basePath.startsWith('.')) {
                    console.log(
                      'trying to resolve path',
                      projectDir,
                      basePath,
                      path.resolve(projectDir, basePath),
                    );
                    basePath = path.resolve(projectDir, basePath);
                  }

                  if (endsWithStar) {
                    basePath = basePath.endsWith('/')
                      ? basePath + '*'
                      : basePath + '/*';
                  }

                  return basePath;
                }),
              ],
            ),
          );
        }
```

2025-02-10 04:42 UTC, nmn commented
Closing in favor of #856

2025-02-10 04:42 UTC, closed without merging